Fix NoSuchMethodError String.stripIndent with Java 11
The method String.stripIndent() requires Java 15 or later.

There was a patch in Nextflow to use instead
String.stripIndent(true) which is implemented by the groovy
runtime and allows backward compatibility with Java 11 and later.

This commit fixes the instances in this training material where
we used `stripIndent`.

Signed-off-by: Marcel Ribeiro-Dantas <mribeirodantas@seqera.io>